---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: Retrieves all posts
      tags:
      - Posts
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    title:
                      type: string
                      nullable: true
                    status:
                      type: integer
                    content:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                      format: date_time
                    updated_at:
                      type: string
                      format: date_time
                  required:
                  - id
                  - user_id
                  - status
                  - created_at
                  - updated_at
    post:
      summary: Creates a post
      tags:
      - Posts
      parameters: []
      responses:
        '201':
          description: post created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                  content:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - user_id
                - status
                - created_at
                - updated_at
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                title:
                  type: string
                  nullable: true
                status:
                  type: integer
                  default: 0
                content:
                  type: string
                  nullable: true
              required:
              - user_id
              - title
              - content
  "/api/v1/posts/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the post
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a post
      tags:
      - Posts
      responses:
        '200':
          description: post found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                  content:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - user_id
                - status
                - created_at
                - updated_at
        '404':
          description: post not found
    put:
      summary: Updates a post
      tags:
      - Posts
      parameters: []
      responses:
        '200':
          description: post updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                  content:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - user_id
                - status
                - created_at
                - updated_at
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - errors
        '404':
          description: post not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                title:
                  type: string
                  nullable: true
                status:
                  type: integer
                content:
                  type: string
                  nullable: true
              required:
              - user_id
              - title
              - content
    delete:
      summary: Deletes a post
      tags:
      - Posts
      responses:
        '204':
          description: post deleted
        '404':
          description: post not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
