default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV.fetch('MYSQL_HOST', 'db') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('MYSQL_USERNAME', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'root') %>

development:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'rails_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'rails_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'rails_production') %>
